/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理员登录（唯一无鉴权写端点；Web UI 用）。 */
        post: operations["login_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codegraph/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_projects"];
        put?: never;
        /** 注册项目（本地路径或 git URL）。 */
        post: operations["register_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codegraph/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codegraph/projects/{id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["index_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codegraph/projects/{id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 代理查询（explore/node 返回 Markdown 文本，其余归一 JSON）。 */
        post: operations["query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codegraph/projects/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sync_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针：进程活着即 200，不查依赖。 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表。 */
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情。 */
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务事件时间线（轮询；SSE 在 Phase 6 按需加）。 */
        get: operations["get_job_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/revive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 复活 dead/failed 任务重跑（仅管理员）。 */
        post: operations["revive_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_documents"];
        put?: never;
        /** 提交 URL 摄取（SSRF 防护在管道内）。 */
        post: operations["submit_url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_document"];
        put?: never;
        post?: never;
        delete: operations["delete_document"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["document_chunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 知识混合检索（结果带文档引用 + 高亮片段）。 */
        post: operations["knowledge_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传文件摄取（multipart，字段名 file）。 */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用量记录（近 500 条）。 */
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/atoms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_atoms"];
        put?: never;
        /** 手工新增原子（人审补充，直接 active）。 */
        post: operations["create_atom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/atoms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_atom"];
        trace?: never;
    };
    "/memory/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** AI 冷启动首选：一站式上下文包（L3+L2+L1 按预算裁剪）。 */
        get: operations["context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/distill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动触发蒸馏链。 */
        post: operations["trigger_distill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_persona"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/persona/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["persona_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/persona/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 回滚分面到历史版本（以新版本落地，历史不可变）。 */
        post: operations["persona_rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_scenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/scenarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_scenario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["memory_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sessions"];
        put?: never;
        /** 写入 L0 会话（AI 客户端的主要写入口）。 */
        post: operations["write_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_session"];
        put?: never;
        post?: never;
        /** 擦除会话（引用它的原子来源标记失效）。 */
        delete: operations["erase_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针：DB 连通 + 迁移已应用才算 ready（compose healthcheck 用）。 */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API key 列表（永不含完整 key）。 */
        get: operations["list_api_keys"];
        put?: never;
        /** 签发 API key。 */
        post: operations["create_api_key_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/api-keys/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 吊销 API key。 */
        post: operations["revoke_api_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** provider 列表（永不含密钥）。 */
        get: operations["list_providers"];
        put?: never;
        /** 注册 LLM provider（key 加密落库）。 */
        post: operations["create_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/providers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 连通性测试：发 1-token chat 探测。 */
        post: operations["test_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取路由表。 */
        get: operations["get_routing"];
        /** 保存路由表。 */
        put: operations["put_routing"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发两步 ingest（sha 命中秒跳过，返回 skipped=true）。 */
        post: operations["ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/lint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lint（只报告）。 */
        post: operations["lint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_page"];
        /** 人工编辑（origin=human，版本递增；LLM 后续只提案不覆盖）。 */
        put: operations["put_page"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/proposals/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 人审合入提案。 */
        post: operations["apply_proposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wiki/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wiki 页面检索。 */
        post: operations["wiki_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiKeyCreated: {
            /** Format: uuid */
            id: string;
            /** @description 明文 key（amk_ 前缀；只在创建响应出现一次） */
            key: string;
            name: string;
        };
        ApiKeyDto: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            key_prefix: string;
            /** Format: date-time */
            last_used_at?: string | null;
            name: string;
            /** Format: date-time */
            revoked_at?: string | null;
            scopes: string[];
        };
        ApplyProposalRequest: {
            content: string;
            slug: string;
            title: string;
        };
        AtomDto: {
            /** Format: float */
            confidence: number;
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            hit_count: number;
            /** Format: uuid */
            id: string;
            kind: string;
            needs_review: boolean;
            /** Format: uuid */
            scenario_id?: string | null;
            source_refs: Record<string, never>;
            status: string;
            /** Format: uuid */
            superseded_by?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description 项目 DTO。 */
        CgProjectDto: {
            /** Format: date-time */
            created_at: string;
            error?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_synced_at?: string | null;
            name: string;
            path: string;
            source_uri: string;
            stats?: Record<string, never> | null;
            status: string;
        };
        CgQueryRequest: {
            /**
             * Format: int32
             * @description explore→max-files；impact→depth
             */
            depth?: number | null;
            /** @description explore | search | node | callers | callees | impact */
            kind: string;
            /** @description 查询文本或符号名 */
            target: string;
        };
        ChunkHit: {
            /** Format: uuid */
            chunk_id: string;
            /** Format: uuid */
            document_id: string;
            document_title: string;
            embed_failed: boolean;
            /** Format: double */
            score: number;
            /** Format: int32 */
            seq: number;
            snippet: string;
        };
        ContextMeta: {
            chars_used: number;
            query?: string | null;
            truncated: boolean;
        };
        ContextPack: {
            /** @description L1：补充原子 */
            atoms: components["schemas"]["AtomDto"][];
            meta: components["schemas"]["ContextMeta"];
            /** @description L3：画像分面（当前版本，全量） */
            persona: components["schemas"]["PersonaVersion"][];
            /** @description L2：相关/最近场景 */
            scenarios: components["schemas"]["ScenarioDto"][];
        };
        CreateApiKeyRequest: {
            name: string;
            scopes?: string[];
        };
        CreateAtomRequest: {
            /** Format: float */
            confidence?: number;
            content: string;
            kind: string;
        };
        CreateProviderRequest: {
            /** @description 明文 API key（只在请求中出现，落库前加密） */
            api_key: string;
            base_url: string;
            is_default?: boolean;
            models?: components["schemas"]["ModelInfo"][];
            name: string;
        };
        DistillRequest: {
            /** @description true 时附带 consolidate */
            full?: boolean;
        };
        DocumentDto: {
            /** Format: date-time */
            created_at: string;
            error?: string | null;
            /** Format: uuid */
            id: string;
            mime?: string | null;
            source_uri: string;
            status: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        ErrorBody: {
            code: string;
            details?: unknown;
            message: string;
            retryable: boolean;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        GraphDto: {
            edges: components["schemas"]["GraphEdge"][];
            nodes: components["schemas"]["GraphNode"][];
        };
        GraphEdge: {
            from_slug: string;
            to_slug: string;
            /** Format: float */
            weight: number;
        };
        GraphNode: {
            page_type: string;
            slug: string;
            title: string;
        };
        HealthBody: {
            status: string;
        };
        IngestAccepted: {
            skipped: boolean;
        };
        IngestRequest: {
            /**
             * Format: uuid
             * @description knowledge 文档 ID（二选一）
             */
            document_id?: string | null;
            /** @description 源文本（也可通过 knowledge 文档 ID） */
            text?: string | null;
            title: string;
        };
        /** @description 任务行。 */
        Job: {
            /** Format: int32 */
            attempts: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            due_at: string;
            error?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: uuid */
            id: string;
            idempotency_key?: string | null;
            kind: string;
            /** Format: date-time */
            locked_at?: string | null;
            locked_by?: string | null;
            /** Format: int32 */
            max_attempts: number;
            payload: Record<string, never>;
            progress?: Record<string, never> | null;
            /** Format: date-time */
            started_at?: string | null;
            status: components["schemas"]["JobStatus"];
            /** Format: int32 */
            visibility_timeout_s: number;
        };
        /** @description 任务事件。 */
        JobEvent: {
            data?: Record<string, never> | null;
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            job_id: string;
            level: string;
            message: string;
            /** Format: date-time */
            ts: string;
        };
        /**
         * @description 任务状态机：
         *     pending → running → succeeded
         *                  ↘ failed（永久错误终态）
         *                  ↘ dead（可重试错误重试耗尽；人工可复活）
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "succeeded" | "failed" | "dead";
        KnowledgeSearchRequest: {
            /** Format: int64 */
            max_items?: number | null;
            query: string;
        };
        LintIssue: {
            detail: string;
            rule: string;
            slug: string;
        };
        LintReport: {
            checked_pages: number;
            issues: components["schemas"]["LintIssue"][];
        };
        LoginRequest: {
            password: string;
        };
        LoginResponse: {
            /** @description 会话 token（ams_ 前缀，7 天有效；只在登录响应出现一次） */
            token: string;
        };
        /** @description 模型信息（provider 配置内）。 */
        ModelInfo: {
            capabilities: string[];
            id: string;
        };
        PersonaVersion: {
            aspect: string;
            content: string;
            /** Format: date-time */
            created_at: string;
            evidence_refs: Record<string, never>;
            /** Format: uuid */
            id: string;
            prompt_version?: string | null;
            /** Format: int32 */
            version: number;
        };
        ProviderDto: {
            base_url: string;
            /** Format: uuid */
            id: string;
            is_default: boolean;
            models: components["schemas"]["ModelInfo"][];
            name: string;
        };
        PutPageRequest: {
            content: string;
            title: string;
        };
        ReadyBody: {
            /** Format: int64 */
            migration_version?: number | null;
            status: string;
        };
        RegisterProjectRequest: {
            name: string;
            /** @description 本地绝对路径或 git URL */
            source_uri: string;
        };
        RollbackRequest: {
            aspect: string;
            /** Format: int32 */
            to_version: number;
        };
        RoutingTable: Record<string, never>;
        ScenarioDto: {
            atom_refs: Record<string, never>;
            /** Format: uuid */
            id: string;
            summary: string;
            topic: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int32 */
            version: number;
        };
        /** @description 统一命中形态。 */
        SearchHit: {
            /** Format: uuid */
            id: string;
            /** @description 额外定位信息（如 atom kind / scenario topic） */
            kind?: string | null;
            /**
             * Format: double
             * @description RRF 融合分
             */
            score: number;
            snippet: string;
            title?: string | null;
        };
        SearchRequest: {
            /** @description 层过滤：["l1","l2","l3"]，空 = 全部 */
            layers?: string[];
            /** Format: int64 */
            max_items?: number | null;
            query: string;
        };
        SearchResponse: {
            l1: components["schemas"]["SearchHit"][];
            l2: components["schemas"]["SearchHit"][];
            l3: components["schemas"]["PersonaVersion"][];
            query: string;
        };
        SessionDto: {
            agent: string;
            content: Record<string, never>;
            /** Format: date-time */
            created_at: string;
            distill_status: string;
            /** Format: uuid */
            id: string;
        };
        SubmitUrlRequest: {
            url: string;
        };
        TestResult: {
            message: string;
            ok: boolean;
        };
        UpdateAtomRequest: {
            /** Format: float */
            confidence?: number | null;
            content?: string | null;
            /** @description 只允许 "archived" / "active" */
            status?: string | null;
        };
        /** @description 用量记账行。 */
        UsageRecord: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: uuid */
            job_id?: string | null;
            /** Format: int32 */
            latency_ms: number;
            model: string;
            /** Format: int64 */
            output_tokens: number;
            provider: string;
            purpose: string;
            /** Format: date-time */
            ts: string;
        };
        WikiPageDto: {
            content: string;
            frontmatter: Record<string, never>;
            /** Format: uuid */
            id: string;
            origin: string;
            page_type: string;
            slug: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int32 */
            version: number;
        };
        WikiSearchRequest: {
            /** Format: int64 */
            max_items?: number | null;
            query: string;
        };
        WriteSessionRequest: {
            agent?: string | null;
            /** @description auto（默认，防抖触发蒸馏）| manual（立即）| off */
            distill?: string;
            /** @description 轮次数组：[{speaker, text, ts?}] */
            turns: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CgProjectDto"][];
                };
            };
        };
    };
    register_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterProjectRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CgProjectDto"];
                };
            };
        };
    };
    get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CgProjectDto"];
                };
            };
        };
    };
    index_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CgProjectDto"];
                };
            };
        };
    };
    query: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CgQueryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    sync_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CgProjectDto"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBody"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                /** @description 任务种类过滤（逗号分隔） */
                kind?: string | null;
                /** @description 状态过滤（逗号分隔: pending,running,succeeded,failed,dead） */
                status?: string | null;
                /** @description 游标（上一页最后一条的 created_at） */
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_job_events: {
        parameters: {
            query?: {
                /** @description 增量游标（上一批最后事件 id） */
                after?: number | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEvent"][];
                };
            };
        };
    };
    revive_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_documents: {
        parameters: {
            query?: {
                status?: string | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"][];
                };
            };
        };
    };
    submit_url: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitUrlRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"];
                };
            };
        };
    };
    get_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"];
                };
            };
        };
    };
    delete_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    document_chunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": [
                        number,
                        string,
                        boolean
                    ][];
                };
            };
        };
    };
    knowledge_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkHit"][];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": number[];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"];
                };
            };
        };
    };
    usage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageRecord"][];
                };
            };
        };
    };
    list_atoms: {
        parameters: {
            query?: {
                kind?: string | null;
                status?: string | null;
                needs_review?: boolean | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtomDto"][];
                };
            };
        };
    };
    create_atom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAtomRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtomDto"];
                };
            };
        };
    };
    update_atom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAtomRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtomDto"];
                };
            };
        };
    };
    context: {
        parameters: {
            query?: {
                /** @description 可选相关性查询；缺省按最近 */
                query?: string | null;
                budget_items?: number | null;
                budget_chars?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextPack"];
                };
            };
        };
    };
    trigger_distill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DistillRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    get_persona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaVersion"][];
                };
            };
        };
    };
    persona_history: {
        parameters: {
            query: {
                aspect: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaVersion"][];
                };
            };
        };
    };
    persona_rollback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaVersion"];
                };
            };
        };
    };
    list_scenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDto"][];
                };
            };
        };
    };
    get_scenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDto"];
                };
            };
        };
    };
    memory_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: {
                agent?: string | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"][];
                };
            };
        };
    };
    write_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteSessionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    erase_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyBody"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_api_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyDto"][];
                };
            };
        };
    };
    create_api_key_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
        };
    };
    revoke_api_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDto"][];
                };
            };
        };
    };
    create_provider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDto"];
                };
            };
        };
    };
    test_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResult"];
                };
            };
        };
    };
    get_routing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingTable"];
                };
            };
        };
    };
    put_routing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingTable"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    graph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphDto"];
                };
            };
        };
    };
    ingest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
        };
    };
    lint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LintReport"];
                };
            };
        };
    };
    list_pages: {
        parameters: {
            query?: {
                page_type?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageDto"][];
                };
            };
        };
    };
    get_page: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageDto"];
                };
            };
        };
    };
    put_page: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutPageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageDto"];
                };
            };
        };
    };
    apply_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyProposalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageDto"];
                };
            };
        };
    };
    wiki_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WikiSearchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageDto"][];
                };
            };
        };
    };
}
